[build]
  # Netlify frontend folder-e giye build korbe
  base = "frontend"
  command = "npm run build"
  publish = "dist"

# React Router / SPA Routing-er 404 error rodh korar jonno
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200